version: 2.1
orbs:
  gruntwork: gruntwork/iac-lib-tests@0.0.1
workflows:
  version: 2.1
  test:
    jobs:
      # By default CircleCI runs jobs on all branches but no tags.
      # We need a filter to ensure jobs run on all tags starting with v.
      - gruntwork/precommit:
          filters:
            tags:
              only: /^v.*/
          context:
            - Gruntwork Admin
      - gruntwork/test:
          requires:
            - gruntwork/precommit
          filters:
            tags:
              only: /^v.*/
          context:
            - Gruntwork Admin
  upgrade-test:
    jobs:
      - gruntwork/precommit:
          filters:
            tags:
              only: /^v.*/
          context:
            - Gruntwork Admin
      - gruntwork/upgrade-test:
          requires:
            - gruntwork/precommit
          filters:
            tags:
              only: /^v.*/
          context:
            - Gruntwork Admin
